export const USER_ROLES = {
  STUDENT: 'STUDENT',
  ADMIN: 'ADMIN',
};

export const SESSION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
};

export const PROFICIENCY_LEVELS = ['BEGINNER', 'INTERMEDIATE', 'EXPERT'];
export const SESSION_DURATIONS = [30, 60, 120];

export const TRUST_SCORE = {
  DEFAULT: 50,
  MIN: 0,
  MAX: 100,
  SESSION_COMPLETE_BONUS: 3,
  NO_SHOW_PENALTY: -8,
  REVIEW_WEIGHT: 0.4,
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 50,
};
